### ISSUE TITLE
Python compiled error, dynamic_lookup was not found

### ISSUE THREAD

**Issue by Joaggi** [dnbaker/frp#4]
Hi Daniel,

I had another error :(. 

I installed python3 with pybind11 for the wrapper to C++

```
apt install python3-dev
apt install python3-pip
pip3 install pybind11
```

With the make command, I received the following error: dynamic_lookup -> this file or directory does not exist.

I searched on google for any advisement, but I did not find any help.

It occurs at the end of the make compilation.

What could be the problem?

**Comment by dnbaker** [comment]
The previous python wrapper was a little brittle, and I've now refactored this to use setup.py, so simply entering the `py` directory and executing `python setup.py install` should install python bindings. (Currently, the only thing exposed is the `ojlt`/`ojlt_d` for performing orthogonal JL transforms.)

Would you let me know if that works? pybind11 shouldn't need system-wide installation since it's a header-only library. If the compiler doesn't find the headers, then maybe `git submodule update --init --recursive` should load dependencies.

**Comment by Joaggi** [comment]
I performed  `git submodule update ` at the beginning.

It seems that with the new commit the errors are gone, but another error seems to occurs.
